name: Create and Publish Container Images

on:
  push:
  schedule:
    - cron: "0 13 * * 1" # every week

jobs:
  build-and-push-image:
    if: ${{ github.owner }} == "varbhat"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the musl image
        run: docker buildx build --load --platform "linux/amd64" . --file amd64-musl.Dockerfile --tag ghcr.io/varbhat/void-container:musl-amd64

      - name: Build the glibc image
        run: docker buildx build --load --platform "linux/amd64" . --file amd64-glibc.Dockerfile --tag ghcr.io/varbhat/void-container:glibc-amd64

      - name: Build the aarch64 musl image
        run: docker buildx build --load --platform "linux/arm64" . --file arm64-musl.Dockerfile --tag ghcr.io/varbhat/void-container:musl-arm64

      - name: Build the aarch64 glibc image
        run: docker buildx build --load --platform "linux/arm64" . --file arm64-glibc.Dockerfile --tag ghcr.io/varbhat/void-container:glibc-arm64

      - name: Push Images
        run: |
          docker push ghcr.io/varbhat/void-container -a
      - name: Create and Push Manifest
        run: |
          docker manifest create ghcr.io/varbhat/void-container:musl ghcr.io/varbhat/void-container:musl-amd64 ghcr.io/varbhat/void-container:musl-arm64
          docker manifest create ghcr.io/varbhat/void-container:glibc ghcr.io/varbhat/void-container:glibc-amd64 ghcr.io/varbhat/void-container:glibc-arm64
          docker manifest create ghcr.io/varbhat/void-container:latest ghcr.io/varbhat/void-container:glibc-amd64 ghcr.io/varbhat/void-container:glibc-arm64
          docker manifest push ghcr.io/varbhat/void-container:musl
          docker manifest push ghcr.io/varbhat/void-container:glibc
          docker manifest push ghcr.io/varbhat/void-container:latest
